### ISSUE TITLE
Lots of boilerplate code + selector suggestion

### ISSUE THREAD

**Issue by cameronb23** [Penor/SneakerBot#2]
Well done so far, although it is a lot of boilerplate code for things like the credentials. You can use a plugin available for IntelliJ and through maven called _lombok_ for automatic getters and setters. In addition, you have one code block that I think could use some improvement.
```java
while(driver.findElement(By.className("sk-fading-circle")).isDisplayed()) {
				try {
					Thread.sleep(5000L);
				} catch (InterruptedException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
		}
```

Instead of checking for the circle solely, maybe checking for captcha is also a good idea.

Other than that, good luck 👍

**Comment by Penor** [comment]
Thanks for the suggestions. I plan on redoing some part of that later on, so keep an eye out. :)
